name: pages-build-deployment

on:
    push:
        branches:
            - master

jobs:
    build-deploy:
        # ubuntu OS を仮想マシン上に用意する
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            # Node.js環境のセットアップを行う
            - name: echo
              uses: actions/setup-node@v1
